services:
  rifleassembly.authentication.web:
    image: rifleassembly-authentication:latest
    build:
      context: .
      dockerfile: Web/RifleAssembly.Authentication.Web/Dockerfile
    ports:
      - "8080:8080" 

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JWT_PRIVATE_KEY_PATH=/secrets/private_key.xml
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./secrets:/secrets:ro
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge