services:
  auth-service:
    image: rifleassembly-authentication:latest
    build:
      context: .
      dockerfile: Web/RifleAssembly.Authentication.Web/Dockerfile
      args:
        - BUILD_CONFIGURATION=Release
    ports:
      - "8082:8080" 

    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:8080
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}

    restart: always
    networks:
      - rifleassembly-network
 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    read_only: true

networks:
  rifleassembly-network:
    external: true
