# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Pipeline Windows

on:
  workflow_dispatch:

env:
  COMPOSE_FILE: src/docker-compose.yml
  API_URL: http://localhost:8080
  JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
  APP_ENVIRONMENT: Staging

jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-config-inline: |
            [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]
          install: true
          driver-opts: image=moby/buildkit:latest         
            
      - name: Build and push with Buildx
        uses: docker/build-push-action@v6          
        with:
          context: ${{ github.workspace }}/src/
          file: ${{ github.workspace }}/src/Web/RifleAssembly.Authentication.Web/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          cache-from: type=local,src=$HOME/.docker/cache
          cache-to: type=local,dest=$HOME/.docker/cache mode=max
          tags: rifleassembly-authentication:latest
          build-args: |
            DOCKER_BUILDKIT=1
          
      - name: Stop old containers
        shell: cmd
        run: docker-compose -f ${{ env.COMPOSE_FILE }} down --rmi local -v --remove-orphans || true

      - name: Build and start
        shell: cmd
        run: |
          docker-compose -f ${{ env.COMPOSE_FILE }} up -d
          
      - name: Check container logs
        shell: cmd
        run: docker-compose logs auth-service
          
    

      - name: Check secret via JS
        uses: actions/github-script@v6
        with:
            script: |
              const secret = process.env.JWT_PRIVATE_KEY;
              if (!secret) {
                  core.setFailed('JWT_PRIVATE_KEY is empty!');
              }
              console.log(`Secret length: ${secret?.length || 0}`);

      - name: Cleanup on failure
        if: failure()
        shell: cmd
        run: |
          docker-compose -f ${{ env.COMPOSE_FILE }} logs
          docker-compose -f ${{ env.COMPOSE_FILE }} down -v
          
    
