# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  COMPOSE_FILE: src/docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: Prepare secrets
        run: |
          mkdir -p secrets
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > secrets/private_key.xml

      - name: Build and start
        run: |
          docker-compose -f $COMPOSE_FILE build
          docker-compose -f $COMPOSE_FILE up -d

      - name: Show logs
        run: |
          docker-compose -f $COMPOSE_FILE logs

      - name: Health Check
        run: |
          echo "Testing API endpoint..."
          sleep 10 
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/health)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "API test passed. HTTP Status Code: $RESPONSE"
          else
            echo "API test failed. HTTP Status Code: $RESPONSE"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f $COMPOSE_FILE down
          rm -rf secrets
    
