# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Pipeline

on: 
  workflow_dispatch:
  push:
    branches: 
    - "master" 
  pull_request:
    branches: 
    - "master" 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
    - uses: docker/setup-buildx-action@v3
    - name: Create .env file
    - run: |
          echo "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}" > .env
    - name: Build Docker images
    - run: docker-compose build
    - name: Start containers
    - run: docker-compose up -d
    - name: Shut down containers
    - run: docker-compose down
    - name: Clean up private key
    - run: rm private_key.xml
    
