# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}" > .env

      - name: Build Docker images
        run: docker compose -f src/docker-compose.yml build

      - name: Start containers
        run: docker compose -f src/docker-compose.yml up -d

      - name: Wait for API to be ready
        run: sleep 10

      - name: Check running containers
        run: docker ps -a

      - name: Check logs if failure occurs
        if: failure()
        run: docker compose -f src/docker-compose.yml logs

      - name: Test API
        run: |
          STATUS=$(curl -v" http://web:5000/api/health)
          if [ $STATUS -ne 200 ]; then
            echo "API test failed. HTTP Status Code: $STATUS"
            exit 1
          fi

      - name: Shut down containers
        run: docker compose -f src/docker-compose.yml down

      - name: Clean up private key
        run: rm .env
    
