# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: Create .xml file
        run: |
          echo "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}" > private_key.xml

      - name: Build Docker images
        run: docker-compose -f src/docker-compose.yml build  

      - name: Start containers
        run: docker-compose -f src/docker-compose.yml up -d

      - name: Check logs
        run: docker-compose -f src/docker-compose.yml logs

      - name: Test API endpoint
        run: |
          echo "Testing API endpoint..."
          sleep 10 
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/health)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "API test passed. HTTP Status Code: $RESPONSE"
          else
            echo "API test failed. HTTP Status Code: $RESPONSE"
            exit 1
          fi

      - name: Shut down containers
        run: docker-compose -f src/docker-compose.yml down

      - name: Clean up private key
        run: rm private_key.xml
    
